### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by JohnDohnut** [woorifisa-service-dev-2nd/backend-1st-book#1]
1. 기능 2, 3에 대하여 검색기능이 동작하지 않음. 
=> "머신러닝 시스템 설계", "제목: 머신러닝 시스템 설계", "머신러닝 시스템 설계 " 등 여러 방법으로 검색해도 '검색 결과가 없습니다.' 출력
==> 사용자로부터 입력 받는 String에 대해 "\n"이 삽입되어 함수가 정상 동작하지 않을 가능성을 염두해야함.
===> 예시 (psuedo code)
===> String input = getInput();
===> if input[-1] == "\n" : input.remove(input[-1])

**Comment by JohnDohnut** [comment]
1. 해결 
=> Mac Terminal 한글입력 관련 문제였음
2. 사용성 개선을 위한 띄어쓰기 처리 
=> "String " 과 "String"이  같은 입력으로 비교되도록 수정 요청

**Comment by rlawncks125** [comment]
이슈처리
